### ISSUE TITLE
ScreenShots

### ISSUE THREAD

**Issue by Chukstart** [waptik/mongoose-cli#12]
The screenshot's link is not working 
where you have said 

 **Please check the examples folder in this project. Screenshots can also be found here**

the link you have placed is 
[https://github.com/waptik/mongoose-cli/blob/master/github/images/screenshots](url)

**Comment by waptik** [comment]
Thanks for drawing my attention to it. It's supposed to be https://github.com/waptik/mongoose-cli/blob/master/.github/images/screenshots .
Done and also i'll go through the docs and fix any irregularities maybe this weekend.

**Comment by Chukstart** [comment]
> Thanks for drawing my attention to it. It's supposed to be https://github.com/waptik/mongoose-cli/blob/master/.github/images/screenshots .
> Done and also i'll go through the docs and fix any irregularities maybe this weekend.
Let me check the link out ...Thankss
