### ISSUE TITLE
Seeders path in config file ".mongooserc"

### ISSUE THREAD

**Issue by excalios** [waptik/mongoose-cli#24]
## What you are doing?
Initialize the mongoose-cli using mongoose init

using .mongooserc from readme
```
const path = require('path');

module.exports = {
  'config': path.resolve('config', 'database.json'),
  'models-path': path.resolve('db', 'models'),
  'seeders-path': path.resolve('db', 'seeders'),
  'migrations-path': path.resolve('db', 'migrations')
}
```
## What do you expect to happen?
Setup the folders for migrations, seeders, etc

## What is actually happening?
Error of:
Unknown arguments: seeders-path, seedersPath

I noticed looking at the code in the core/yargs code that it actually doesn't exist. If this is intentional please remove it from the readme thank you

__Mongoosejs CLI version:__ Latest
__Mongoose version:__ Latest

**Comment by waptik** [comment]
Sorry, it wasn't left out intentionally.
I'll fix it and push a new version of the package by tomorrow same time.
Thanks for the notice.

**Comment by excalios** [comment]
The seeders-path config now works
Thank you for the update and fast response

**Comment by waptik** [comment]
Sure no problem. Feel free to open a new issue if anything happens.
